[web_servers]
web ansible_host=98.87.160.74 ansible_user=ubuntu

[db_servers]
db ansible_host=10.0.2.137 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i /home/ubuntu/mern-key-new.pem -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@98.87.160.74"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
